=== swaldmann/MasterThesis/server/JSON Schemes/JoinProblem.schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "title": "JoinProblem",
  "type": "object",
  "required": [
    "problemID",
    "neighbors",
    "numberOfRelations",
    "relations",
    "selectivities"
  ],
  "properties": {
    "problemID": {
      "type": "number"
    },
    "neighbors": {
      "type": "object",
      "patternProperties": {
        "^[0-9]+$": {
          "type": "string"
        }
      }
    },
    "numberOfRelations": {
      "type": "number"
    },
    "relations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "cardinality": {
            "type": "number"
          },
          "name": {
            "type": "string"
          },
          "problemID": {
            "type": "number"
          },
          "relationID": {
            "type": "number"
          }
        },
        "additionalProperties": false
      }
    },
    "selectivities": {
      "type": "object",
      "patternProperties": {
        "^[0-9,]+$": {
          "type": "number"
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== swaldmann/MasterThesis/server/joinproblems/star_10.json
[
    {
        "problemID": 0,
        "neighbors": {
            "0": "1,2,3,4,5,6,7,8,9",
            "1": "0",
            "2": "0",
            "3": "0",
            "4": "0",
            "5": "0",
            "6": "0",
            "7": "0",
            "8": "0",
            "9": "0"
        },
        "numberOfRelations": 10,
        "relations": [
            {
                "cardinality": 554073.0860513153,
                "name": "<unknown>",
                "problemID": 0,
                "relationID": 0
            },
            {
                "cardinality": 188548.7114164056,
                "name": "<unknown>",
                "problemID": 0,
                "relationID": 1
            },
            {
                "cardinality": 62990.742835979436,
                "name": "<unknown>",
                "problemID": 0,
                "relationID": 2
            },
            {
                "cardinality": 21092.007781042135,
                "name": "<unknown>",
                "problemID": 0,
                "relationID": 3
            },
            {
                "cardinality": 14467.13436269978,
                "name": "<unknown>",
                "problemID": 0,
                "relationID": 4
            },
            {
                "cardinality": 6761.230546061097,
                "name": "<unknown>",
                "problemID": 0,
                "relationID": 5
            },
            {
                "cardinality": 4011.368000267313,
                "name": "<unknown>",
                "problemID": 0,
                "relationID": 6
            },
            {
                "cardinality": 2639.119216814652,
                "name": "<unknown>",
                "problemID": 0,
                "relationID": 7
            },
            {
                "cardinality": 135.1106833796348,
                "name": "<unknown>",
                "problemID": 0,
                "relationID": 8
            },
            {
                "cardinality": 7.70954008593561,
                "name": "<unknown>",
                "problemID": 0,
                "relationID": 9
            }
        ],
        "selectivities": {
            "0,1": 4.841206836495829e-06,
            "0,2": 1.0156471790838367e-05,
            "0,3": 5.332091530839734e-06,
            "0,4": 3.3064491552997506e-07,
            "0,5": 4.393127072571011e-05,
            "0,6": 0.00019896101696387979,
            "0,7": 4.162818797432224e-05,
            "0,8": 0.0072615256413159504,
            "0,9": 0.09414815347234863
        }
    },
    {
        "problemID": 1,
        "neighbors": {
            "0": "1,2,3,4,5,6,7,8,9",
            "1": "0",
            "2": "0",
            "3": "0",
            "4": "0",
            "5": "0",
            "6": "0",
            "7": "0",
            "8": "0",
            "9": "0"
        },
        "numberOfRelations": 10,
        "relations": [
            {
                "cardinality": 243252.66846374024,
                "name": "<unknown>",
                "problemID": 1,
                "relationID": 0
            },
            {
                "cardinality": 170065.87081079365,
                "name": "<unknown>",
                "problemID": 1,
                "relationID": 1
            },
            {
                "cardinality": 89415.80327347567,
                "name": "<unknown>",
                "problemID": 1,
                "relationID": 2
            },
            {
                "cardinality": 44662.312733475614,
                "name": "<unknown>",
                "problemID": 1,
                "relationID": 3
            },
            {
                "cardinality": 17813.41038583298,
                "name": "<unknown>",
                "problemID": 1,
                "relationID": 4
            },
            {
                "cardinality": 9589.45941873084,
                "name": "<unknown>",
                "problemID": 1,
                "relationID": 5
            },
            {
                "cardinality": 4004.64670679615,
                "name": "<unknown>",
                "problemID": 1,
                "relationID": 6
            },
            {
                "cardinality": 2665.0451531955096,
                "name": "<unknown>",
                "problemID": 1,
                "relationID": 7
            },
            {
                "cardinality": 255.77697278628716,
                "name": "<unknown>",
                "problemID": 1,
                "relationID": 8
            },
            {
                "cardinality": 15.073253554103395,
                "name": "<unknown>",
                "problemID": 1,
                "relationID": 9
            }
        ],
        "selectivities": {
            "0,1": 4.496539907980801e-06,
            "0,2": 1.4000071862224854e-06,
            "0,3": 1.8402613176620767e-05,
            "0,4": 5.580450193370189e-05,
            "0,5": 1.5549779179012947e-05,
            "0,6": 0.00021785412895143307,
            "0,7": 0.00011877864224530528,
            "0,8": 0.003117090278116779,
            "0,9": 0.020029725221143768
        }
    }
]

=== swaldmann/MasterThesis/server/joinproblems/tree_3.json
{
 "problemID": 0,
 "neighbors": {
  "0": "1,2",
  "1": "0",
  "2": "0"
 },
 "numberOfRelations": 3,
 "relations": [
  {
   "cardinality": 4377.141871869801,
   "name": "unknown",
   "problemID": 0,
   "relationID": 0
  },
  {
   "cardinality": 4246.374970712657,
   "name": "unknown",
   "problemID": 0,
   "relationID": 1
  },
  {
   "cardinality": 6868.230728671094,
   "name": "unknown",
   "problemID": 0,
   "relationID": 2
  }
 ],
 "selectivities": {
  "0,1": 0.06563701921747622,
  "0,2": 0.15651925473279124
 }
}
